### ISSUE TITLE
Implement user mapping between MM and OpsGenie

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-app-opsgenie#5]
Yes, I like this.  Let me summarize to see if we agree
- On successful configure by sysadmin the app will show its Settings.
- One of the settings is "Link users by email address" On/Off boolean, default = On
- The description of this setting says "Allow Mattermost users to update alerts in OpsGenie if their email in Mattermost matches their email in OpsGenie"
- If the switch is on then allow email user linking, and allow users with matching email addresses to update records in OpsGenie from Mattermost.  Also, allow users in Mattermost to subscribe channels to OpsGenie Notifications if they have the correct permissions in OpsGenie
- If the switch is off then the buttons shown on OpsGenie notifications will not be shown.  Only Sysadmins in Mattermost can Subscribe a channel to notifications from OpsGenie.

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/dgp3i5m417nxmq4ukxuee31jzr) *by @asatkinson*._

**Comment by mickmister** [comment]
*@mickmister attached a* [message](https://community.mattermost.com/_redirect/pl/e7gkbke8x7r5z8cn35etdc5cho) *from @mickmister*

Then it's up to us to design the "rules" around this. @lizsegura98 mentioned team membership. The Jira plugin supports further rules such as "Jira user role" to limit certain features to specific groups of users. Maybe OpsGenie has a similar concept.

**Comment by srkgupta** [comment]
Hi @mickmister @LizSegura98

> If the switch is on then allow email user linking, and allow users with matching email addresses to update records in OpsGenie from Mattermost. Also, allow users in Mattermost to subscribe channels to OpsGenie Notifications if they have the correct permissions in OpsGenie

Just to be more precise here, we should also ensure that the user in OpsGenie is active, i.e has verified and confirmed their account.

**Comment by LizSegura98** [comment]
This was worked on current PR [(Fix/security issues)](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1/files)
@srkgupta

**Comment by LizSegura98** [comment]
This issue was solved in PR [(fix/security_issues)](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1)
Merged today - Feb 1st 

[srkgupta comment](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1#pullrequestreview-1278498556)
